export const data = [
    {
        "id": "1",
        "price": "500",
        "rating": "3.1",
        "color": "blue",
        "ratingCount": "200",
        "dishCount": "20",
        "image": "https://knowbbies.com/storage/courses/June2018/35118898_1675576969163519_65233698458435584_n-medium.jpg",
        "format": "LunchBox",
        "occassion": "Baby Shower",
        "type": "nonveg",
        "distance": "6"

    },
    {
        "id": "2",
        "price": "900",
        "rating": "5",
        "color": "green",
        "ratingCount": "299",
        "dishCount": "10",
        "image": "https://img.theweek.in/content/dam/week/webworld/feature/lifestyle/2017/december/chicken-biriyani.jpg",
        "format": "SnackBox",
        "occassion": "House Warming",
        "type": "nonveg",
        "distance": "6"
    },
    {
        "id": "3",
        "price": "700",
        "rating": "3.5",
        "color": "blue",
        "ratingCount": "299",
        "dishCount": "10",
        "image": "https://images.herzindagi.info/image/2020/May/summer.jpg",
        "format": "FoodTrucks",
        "occassion": "House Party",
        "type": "nonveg",
        "distance": "3"
    },
    {
        "id": "4",
        "price": "100",
        "rating": "2",
        "color": "#e52364",
        "ratingCount": "175",
        "dishCount": "12",
        "image": "https://asset20.ckassets.com/blog/wp-content/uploads/sites/5/2019/12/Healthy-food-items-on-Swiggy.jpg",
        "format": "Buffet",
        "occassion": "Birthday celebration",
        "type": "veg",
        "distance": "1"
    },
    {
        "id": "5",
        "price": "310",
        "rating": "2",
        "color": "#e52364",
        "ratingCount": "555",
        "dishCount": "12",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRzE6rjbvY21wYDrSPWhKgu13SS-80bHvvzrw&usqp=CAU",
        "format": "Buffet",
        "occassion": "Baby Shower",
        "type": "veg",
        "distance": "4"
    },
    {
        "id": "6",
        "price": "100",
        "rating": "5",
        "color": "green",
        "ratingCount": "323",
        "dishCount": "12",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQXglh175PqV_jA__yalRqW8G362bapBsjsKg&usqp=CAU",
        "format": "Buffet",
        "occassion": "Baby Shower",
        "type": "veg",
        "distance": "7"
    },

];

export const commonOrderData = [
    {
        "id": "1",
        "city": "IndiraNagar",
        "hotel": "Baba Da Dhaba",
        "price": "500",
        "rating": "3.1",
        "ratingCount": "200",
        "dishCount": "20",
        "image": "https://www.listchallenges.com/f/lists/3d06c742-15cc-49b2-8845-7ef42d0c9f97.jpg",
        "format": "Lunch Box",
        "occassion": "Baby Shower",

    },
    {
        "id": "2",
        "city": "Kormangala",
        "hotel": "Hyderabadi Biryani Shop",
        "price": "900",
        "rating": "5",
        "ratingCount": "299",
        "dishCount": "10",
        "image": "https://www.rd.com/wp-content/uploads/2018/12/shutterstock_1161597079.jpg",
        "format": "Snack Box",
        "occassion": "House Warming",
    },
    {
        "id": "3",
        "city": "Venkatapura",
        "hotel": "Punjabi Dhaba",
        "price": "700",
        "rating": "5",
        "ratingCount": "299",
        "dishCount": "10",
        "image": "https://i1.wp.com/www.eatthis.com/wp-content/uploads/media/images/ext/305133437/burger-king-spread.jpg?fit=1024%2C750&ssl=1",
        "format": "Food Trucks",
        "occassion": "House Party",
    },
    {
        "id": "4",
        "city": "Teachers Colony",
        "hotel": "Malabar Hotel",
        "price": "100",
        "rating": "2",
        "ratingCount": "156",
        "dishCount": "16",
        "image": "https://asset20.ckassets.com/blog/wp-content/uploads/sites/5/2019/11/1-1.jpg",
        "format": "Buffet",
        "occassion": "Birthday celebration",
    },
    {
        "id": "5",
        "city": "Domlur",
        "hotel": "Momo Corner",
        "price": "490",
        "rating": "4.5",
        "ratingCount": "556",
        "dishCount": "17",
        "image": "https://post.healthline.com/wp-content/uploads/2020/03/adhd-foods-to-avoid_thumb-732x549.jpg",
        "format": "Food Trucks",
        "occassion": "Birthday celebration",
    },
    {
        "id": "6",
        "city": "Electron City",
        "hotel": "Kailash Dhaba",
        "price": "300",
        "rating": "5",
        "ratingCount": "455",
        "dishCount": "12",
        "image": "https://www.dosafactorymenu.com/blog-admin/images/indian-food-items-apt-for-everyone041641.jpeg",
        "format": "Food Trucks",
        "occassion": "Dinner Party",
    },

];